### ISSUE TITLE
M1 3.4 Non-functional Requirements

### ISSUE THREAD

**Issue by kyethefluffyowl** [P4-4-Team-project/team4WMS#10]

**Comment by kyethefluffyowl** [comment]
Can help check that the non-functional requirements are sound and complete? Feel free to add more also! Thank you! @jodiesa @ZafrullaKamil @jianweiiii

**Comment by jianweiiii** [comment]
Added and changed some of the requirements! please do help check it as well :) @kyethefluffyowl
