### ISSUE TITLE
M1 4.1 Software Estimation

### ISSUE THREAD

**Issue by kyethefluffyowl** [P4-4-Team-project/team4WMS#11]

**Comment by kyethefluffyowl** [comment]
Completed estimation on software. Posted results [here](https://docs.google.com/spreadsheets/d/1ttnExlVuH6tb8IocAAJzb95KOq3m-1jv/edit?usp=sharing&ouid=104450121481375238359&rtpof=true&sd=true). 

Can help me look through to make sure the calculations are correct? @jodiesa

**Comment by jodiesa** [comment]
@kyethefluffyowl okay noted

**Comment by jodiesa** [comment]
@kyethefluffyowl looks good!
