### ISSUE TITLE
M1 5 Individual Members Task Reflection

### ISSUE THREAD

**Issue by ZafrullaKamil** [P4-4-Team-project/team4WMS#12]

**Comment by jianweiiii** [comment]
Finish my part on the task reflection!
@ZafrullaKamil @jodiesa @kyethefluffyowl  Please help check for any error :)

**Comment by kyethefluffyowl** [comment]
Looks good! Finish my part on task reflection also! 
@jodiesa @jianweiiii @ZafrullaKamil Thanks for checking for me also <3
