### ISSUE TITLE
M1 Meeting Minutes

### ISSUE THREAD

**Issue by jianweiiii** [P4-4-Team-project/team4WMS#22]

**Comment by kyethefluffyowl** [comment]
Posted onto the new page in the project's wiki

**Comment by kyethefluffyowl** [comment]
Attached is the link to the full minutes.
https://docs.google.com/document/d/1CJFriLcSKfvBt2GJoowuItOuUFIZ4sJd/edit?usp=sharing&ouid=104450121481375238359&rtpof=true&sd=true

**Comment by kyethefluffyowl** [comment]
@jianweiiii Pls check <3

**Comment by jianweiiii** [comment]
@kyethefluffyowl looks good to me!
