### ISSUE TITLE
M2 Retrospection

### ISSUE THREAD

**Issue by jodiesa** [P4-4-Team-project/team4WMS#36]

**Comment by kyethefluffyowl** [comment]
@jodiesa @jianweiiii @ZafrullaKamil 
Let's call and talk about these questions.

1. What went well in Milestone TWO? 

2. What could be improved?
Team dynamics, team management, task allocation and management, etc.

3. What will we commit to improve in the final milestone?

**Comment by kyethefluffyowl** [comment]
Thanks for the call guys! Here's a summary of what was talked about.

1. Milestone TWO functioned like a well oiled machine where we all gathered together to work on the diagrams as one, and hence was able to complete large tasks in less time. For that, I would like to say thank you :)

2. Time management was a common feedback from the call. Knowing that each one of us has other projects to handle, we left the tasks till a little too close for comfort till the deadline. Perhaps for Milestone THREE we could split up the tasks and work on it when we are free and just update each other instead.

3. Communication and task allocation will be improved to make sure everyone is aware of the progress of the final milestone. Hopefully this resolves the stress we encountered from grinding the midnight oil for milestone TWO.

We're almost there folks. We can do it! :D

**Comment by kyethefluffyowl** [comment]
As motivation, have a cat pic to de-stress, even if it's just a tiny bit. :)
@kyethefluffyowl @jodiesa @ZafrullaKamil @jianweiiii 

![Image](https://user-images.githubusercontent.com/23163333/203098079-c03dd39b-e81a-4e71-93db-f3b07eae1191.png)

**Comment by jodiesa** [comment]
awesome picture 👍  stay strong guys!!
