### ISSUE TITLE
4.2 Prototype

### ISSUE THREAD

**Issue by jodiesa** [P4-4-Team-project/team4WMS#38]

**Comment by kyethefluffyowl** [comment]
@ZafrullaKamil @jodiesa @jianweiiii GUYS HERES THE LINK

**Comment by kyethefluffyowl** [comment]
THANKS FOR HELPING GUYS <3

**Comment by kyethefluffyowl** [comment]
OKAY DONE VIDEO: https://youtu.be/tp5vtiB-OVA

**Comment by jianweiiii** [comment]
GOOD JOB @kyethefluffyowl 
reviewed the video!!! is perfect!
