### ISSUE TITLE
4.3 Create test cases

### ISSUE THREAD

**Issue by jodiesa** [P4-4-Team-project/team4WMS#39]

**Comment by jianweiiii** [comment]
@kyethefluffyowl @jodiesa @ZafrullaKamil  HI GUYS! i have done up the test cases please do help check on it :)

**Comment by ZafrullaKamil** [comment]
I have added comments where I feel that may have been missed. Looks great overall!

**Comment by kyethefluffyowl** [comment]
Thank you! Great comments!
