### ISSUE TITLE
M2 3.3 Sequence Diagram

### ISSUE THREAD

**Issue by jodiesa** [P4-4-Team-project/team4WMS#40]

**Comment by jodiesa** [comment]
Hey team, the sequence diagram will be delegated as follows:
Detailed use case description 1-5 @kyethefluffyowl 
Detailed use case description 6-10 @jianweiiii 
Detailed use case description 11-16 @ZafrullaKamil 
Detailed use case description 17-22 @jodiesa 

thanks!

**Comment by jianweiiii** [comment]
im done with use case 6-10. Please check @jodiesa !!! thank you!

**Comment by kyethefluffyowl** [comment]
Hao le pls check @jodiesa <3

**Comment by ZafrullaKamil** [comment]
Hi, I've done my part too, can @jodiesa help me check too?

I've also looked through the rest and it looks good! @kyethefluffyowl @jianweiiii

**Comment by jodiesa** [comment]
looks good guys~ thank you 

@kyethefluffyowl @ZafrullaKamil @jianweiiii

**Comment by ZafrullaKamil** [comment]
After going through all the sequence diagrams created, let's pick a few that is thorough and showcases the important interactions between our actors and classes. We shall go through them together and finalise it to include in the report.

@kyethefluffyowl @jodiesa @jianweiiii

**Comment by kyethefluffyowl** [comment]
@ZafrullaKamil I VOTE 3 and 5 🤪💥

**Comment by jodiesa** [comment]
yea i agree! How about 6? @ZafrullaKamil @kyethefluffyowl

**Comment by jianweiiii** [comment]
@ZafrullaKamil I think that Use Case 8 and 9 is quite important! we should definitely show that in our M2 report!

**Comment by jodiesa** [comment]
okay thank you guys! @kyethefluffyowl @jianweiiii @ZafrullaKamil
