### ISSUE TITLE
M2 3.1 Class Diagram

### ISSUE THREAD

**Issue by jodiesa** [P4-4-Team-project/team4WMS#41]

**Comment by kyethefluffyowl** [comment]
Link to class diagram can be found [here](https://app.diagrams.net/#G1e9wj3vCvaxwN31z8qutan3W5sR7QiZYe).

**Comment by ZafrullaKamil** [comment]
The design patterns have been reflected in the class diagrams.

**Comment by ZafrullaKamil** [comment]
Class diagrams have been updated for M3 to include interface classes for the design patterns as we only thought that entity control and boundary classes were allowed:(
