### ISSUE TITLE
M2 Update Gantt Chart

### ISSUE THREAD

**Issue by jodiesa** [P4-4-Team-project/team4WMS#42]

**Comment by jodiesa** [comment]
Hey guys I updated the Gantt chart pls help to take a look thank you @ZafrullaKamil @kyethefluffyowl @jianweiiii

**Comment by kyethefluffyowl** [comment]
Update more of the percentages for several tasks!

**Comment by jianweiiii** [comment]
Everything looks good!!

**Comment by ZafrullaKamil** [comment]
Looks good to me! let's make sure that it coincides with our software estimation for each developer.
