### ISSUE TITLE
M2 3.5 Communication Diagram

### ISSUE THREAD

**Issue by jodiesa** [P4-4-Team-project/team4WMS#43]

**Comment by jianweiiii** [comment]
hi @jodiesa @kyethefluffyowl i have finished up 1 of the communication diagram!!! please do check through and give feedback if possible! thank you!

**Comment by kyethefluffyowl** [comment]
Thank you! Made some edits together with the rest of team!

**Comment by jodiesa** [comment]
noted, thank you!

**Comment by kyethefluffyowl** [comment]
Completed for m2! Thanks guys <3 @jodiesa @jianweiiii @ZafrullaKamil
