### ISSUE TITLE
4.1 Wireframe

### ISSUE THREAD

**Issue by jodiesa** [P4-4-Team-project/team4WMS#46]

**Comment by jodiesa** [comment]
Hi guys, we can collab on the wireframe using this link 
: https://www.figma.com/file/t3FCB4Sp9Z77a1xoP0is7N/Untitled?node-id=0%3A1

thank you 💯

**Comment by jodiesa** [comment]
@kyethefluffyowl @ZafrullaKamil @jianweiiii Please help to check through the wireframes :) thank you

**Comment by kyethefluffyowl** [comment]
LOOK GREAT TY

**Comment by jianweiiii** [comment]
LOOKS GOOD.
GOOD JOB @jodiesa

**Comment by ZafrullaKamil** [comment]
Interaction is working well in the figma! <3
