### ISSUE TITLE
M1 3.3 Use Case Model

### ISSUE THREAD

**Issue by kyethefluffyowl** [P4-4-Team-project/team4WMS#7]

**Comment by kyethefluffyowl** [comment]
Need edit the use cases after client meeting

**Comment by ZafrullaKamil** [comment]
It seems that the actors in the use case model is unclear as employee and staff is not a good term to use. Can @jianweiiii help me take a look and give suggestions to improve?

**Comment by jianweiiii** [comment]
i think we can use the job title given by the client, else we can identify them as employee as a whole! @ZafrullaKamil
